language: node_js
node_js:
- 'stable'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  yarn: true
env:
  global:
  - JOBS=1

before_install:
- npm install -g bower
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- bower install
- yarn install --non-interactive
script:
- yarn test
